return {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,
	["Block Pet Gift"] = true,
	Collect_Cooldown = 60,
	["Low Cpu"] = true,
	["Auto Rejoin"] = true,
	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 400,
		["Destroy Until"] = 400,
		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
			-- for the event
			Bamboo = 4,
			Coconut = 15,
			Mushroom = 4,
			Glowthorn = 4,
			Tomato = 15,
			Pumpkin = 4,
			Pepper = 4,
			Cacao = 15,
			Apple = 15,
			Romanesco = 4,
			["Elder Strawberry"] = 4,
			["Burning Bud"] = 4,
			["Giant Pinecone"] = 4,
			Corn = 4,
			["Sugar Apple"] = 4,
			["Ember Lily"] = 4,
			["Dragon Fruit"] = 15,
			Sunbulb = 8,
			["Orange Tulip"] = 4,
			Blueberry = 15,
			Watermelon = 4,
			Mango = 15,
			Cactus = 4,
			Strawberry = 15,
			Beanstalk = 4,
			Lightshoot = 4,
			Grape = 4,
			Daffodil = 4
		}
	},
	Seed = {
		Buy = {
			Mode = "Auto", -- Custom , Auto
			Custom = { -- any fruit u need to place
				"Carrot"
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight"
			}
		}
	},
	["Seed Pack"] = {
		Locked = {
			["Enchanted Seed Pack"] = 10,
		}
	},
Events = {
		-- MaxMoney_Restocks = 10_000_000,
		
		Shop = { -- un comment to buy
			"Evo Beetroot I",
			"Evo Blueberry I",
			"Evo Pumpkin I",
			"Evo Mushroom I",
		},
		["Traveling Shop"] = {
			"Bee Egg",
			"Paradise Egg", 
			"Rare Summer Egg", 
			"Common Summer Egg"
		},
		Craft = {
			"Enchanted Chest",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},
	Gear = {
		Buy = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Medium Treat",
			"Medium Toy"
		},
		Lock = { "Master Sprinkler", "Godly Sprinkler", "Advanced Sprinkler", "Basic Sprinkler", "Lightning Rod" }
	},
	Eggs = {
		Place = {
			"Jungle Egg",
			-- "Fall Egg"
			--"Anti Bee Egg",
			--"Rare Egg",
			--"Common Summer Egg",
			--"Enchanted Egg",
			--"Sprout Egg",
			--"Legendary Egg",
			--"Rare Summer Egg",
			--"Paradise Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			--"Oasis Egg",
			--"Night Egg",
			--"Bug Egg",
			--"Primal Egg",
			--"Dinosaur Egg",
		},
		Buy = {
			"Bug Egg",
			"Bee Egg",
			"Paradise Egg",
			"Legendary Egg",
			"Mythical Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg"
		}
	},
	Pets = {
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 55,
		["Upgrade Slot"] = {
			["Little Auto Equip"] = true,
			["Pet"] = {
				["Starfish"] = { 1, 75, 1, true }
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				-- ["Peach Wasp"] = {1,100,1},
				--["Glimmering Sprite"] = {3,100},
				["Rooster"] = { 8, 100, 1 }
				--["Sunny-Side Chicken"] = {1,100},
				--["Wasp"] = {1,100},
				--["Tarantula Hawk"] = {1,100},
			}
		},
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		Locked_Pet_Age = 75,
		Locked = {
			"Red Panda",
			"Barn Owl",
			"Swan",
			"Marmot",
			"Space Squirrel",
			"Sugar Glider",
			"Drake",
			"Phoenix",
			["Shroomie"] = 3,
			"Cockatrice",
			"Griffin",
			"Peach Wasp",
			"Apple Gazelle",
			"Green Bean",
			"Lemon Lion",
			"Golden Goose",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"T-Rex",
			"Spinosaurus",
			"Fennec Fox",
			"Mimic Octopus",
			"Disco Bee",
			"Butterfly",
			"Raccoon",
			"Queen Bee",
			"Dragonfly",
			"Red Fox",
			"Ankylosaurus",
			"Dilophosaurus",
			"Brontosaurus",
			"Hyacinth Macaw",
			"Moth",
			"Moon Cat",
			"Night Owl",
			"Blood Owl",
			"Blood Kiwi",
			"Cooked Owl",
			"Pterodactyl",
			"Chicken Zombie",
			"Raiju",
			["Wasp"] = 10,
			["Tarantula Hawk"] = 10,
			"Axolotl",
			"Echo Frog",
			"Hamster",
			["Pixie"] = 5,
			["Maneki-neko"] = 2,
			["Hotdog Daschund"] = 2,
			["Sunny-Side Chicken"] = 3,
			["Mochi Mouse"] = 1,
			["Koi"] = 2,
			["Bacon Pig"] = 1,
			["Junkbot"] = 1,
			["Starfish"] = 5,
			["Kappa"] = 1,
			["Tanchozuru"] = 2,
			["Praying Mantis"] = 5,
			["Rooster"] = 8,
			["Seal"] = 2,
			["Chicken"] = 2,
			["Golem"] = 1,
			["Bagel Bunny"] = 2,
			["Peacock"] = 3,
			["Ostrich"] = 4,
			["Sea Turtle"] = 3,
			["Scarlet Macaw"] = 2,
			["Turtle"] = 6,
			["Monkey"] = 6
		},
		LockPet_Weight = 8,
		Instant_Sell = {
			"Glimmering Sprite",
			"Kodama",
			"Capybara",
			"Sushi Bear",
			"Polar Bear",
			"Snail",
			"Squirrel",
			"Gorilla Chef",
			"Spaghetti Sloth",
			"Imp",
			"Mandrake",
			"Jackalope",
			"Flamingo",
			"Toucan",
			"Orangutan",
			"Dairy Cow",
			"Bagel Bunny",
			"Seagull",
			"Caterpillar",
			"Corrupted Kodama",
			"Golem",
			"Bacon Pig",
			"Crab",
			"Hotdog Daschund",
			"Elk",
			"Bunny",
			"Dog",
			"Cow",
			"Sea Otter",
			"Silver Monkey",
			"Spotted Deer",
			"Pig",
			"Ladybug",
			"Orange Tabby",
			"Giant Ant",
			"Pixie"
		}
	},
	Webhook = {
		UrlPet = "",
		UrlSeed = "xxx",
		PcName = "LUCKY",
		Noti = {
			Seeds = { "Sunflower", "Dragon Pepper", "Elephant Ears" },
			SeedPack = { "Idk" },
			Pets = { "Lobster Thermidor", "French Fry Ferret" },
			Pet_Weight_Noti = false
		}
	}
}
