return {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,
	["Block Pet Gift"] = true,
	Collect_Cooldown = 30,
	["Low Cpu"] = true,
	["Auto Rejoin"] = true,
	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 400,
		["Destroy Until"] = 400,

		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
			-- for the event
			Bamboo = 4,
			Coconut = 15,
			Mushroom = 4,
			Glowthorn = 4,
			Tomato = 15,
			Pumpkin = 4,
			Pepper = 4,
			Cacao = 15,
			Apple = 15,
			Romanesco = 4,
			["Elder Strawberry"] = 4,
			["Burning Bud"] = 4,
			["Giant Pinecone"] = 4,
			Corn = 4,
			["Sugar Apple"] = 4,
			["Ember Lily"] = 4,
			["Dragon Fruit"] = 15,
			Sunbulb = 8,
			["Orange Tulip"] = 4,
			Blueberry = 15,
			Watermelon = 4,
			Mango = 15,
			Cactus = 4,
			Strawberry = 15,
			Beanstalk = 4,
			Lightshoot = 4,
			Grape = 4,
			Daffodil = 4,
		}
	},
	Seed = {
		Buy = {
			Mode = "Auto", -- Custom , Auto
			Custom = { -- any fruit u need to place
				"Carrot",
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight",
			}
		}
	},
	["Seed Pack"] = {
		Locked = {
		}
	},
	Events = {
		["Fall Event"] = {
			Minimum_Money = 10_000_000, -- minimum money to start play this event
		},
		["Fairy Event"] = {
			Minimum_Money = 10_000_000, -- minimum money to start play this event
			Rewards_Item = { -- top mean select first
				"Enchanted Seed Pack",
				"Pet Shard Glimmering",
				"Enchanted Egg",
				"Mutation Spray Glimmering",
				"FairyPoints",
				"Fairy Targeter",
			},
			Upgrade = {
				Mode = "Order", -- Order (mean will up on order), Chepest, Highest
				Order = { -- top upgrade first, not put mean not upgrade
					"Fairy Spawn Amount",
					"Loose Fairy Spawn Amount",
					"Glimmer Multiplier",
					"Fairy Event Duration",
				},
				Limit = {
					["Glimmer Multiplier"] = 5, -- max 10
					["Loose Fairy Spawn Amount"] = 10, -- max 10
					["Fairy Event Duration"] = 10, -- max 10
					["Fairy Spawn Amount"] = 9, -- max 9
				}
			},
			
			Minimum_Fairy_Point_Restock = 10000, -- if fairy point more then this will restock
			Catch_Fairy_Before_Restock = 51, -- fr it 50 but to be sure i put 51
		},
		MaxMoney_Restocks = 480_000_001,
		
		Shop = { -- un comment to buy
			"Fall Egg",

			"Enchanted Chest",
			"Pet Shard Glimmering",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Drake",
			"Pixie Faern",
			"Untold Bell",
			"Luminous Sprite",
			"Mutation Spray Luminous",
			"Luminous Wand",

			"Sprout Seed Pack",
			"Sprout Egg",
			-- "Mandrake",
			"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			--["Spriggan"] = 8,
			-- Friend Shop
			"Skyroot Chest",
			"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
			"Bee Egg",
			"Paradise Egg", 
			"Rare Summer Egg", 
			"Common Summer Egg"
		},
		Craft = {
			"Enchanted Chest",
			"Fairy Net",
			"Enchanted Egg",
			"Enchanted Seed Pack",
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},


	Gear = {
		Buy = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Medium Treat",
			"Medium Toy",
		},
		Lock = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
		},
	},
	Eggs = {
		Place = {
			"Fall Egg",
			--"Anti Bee Egg",
			--"Rare Egg",
			--"Common Summer Egg",
			--"Enchanted Egg",
			--"Sprout Egg",
			--"Legendary Egg",
			--"Rare Summer Egg",
			--"Paradise Egg",
			--"Gourmet Egg",
			--"Zen Egg",
			--"Oasis Egg",
			--"Night Egg",
			--"Bug Egg",
			--"Primal Egg",
			--"Dinosaur Egg",
		},
		Buy = {
			"Bug Egg",
			"Bee Egg",
			"Paradise Egg",
			"Legendary Egg",
			"Mythical Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
		}
	},
	Pets = {
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 55,
		["Upgrade Slot"] = {
			["Little Auto Equip"] = true,
			["Pet"] = {
				["Starfish"] = {1,75,1,true},
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				-- ["Peach Wasp"] = {1,100,1},
				--["Glimmering Sprite"] = {3,100},
				["Rooster"] = {8,100,1},
				--["Sunny-Side Chicken"] = {1,100},
				--["Wasp"] = {1,100},
				--["Tarantula Hawk"] = {1,100},
			},
		},
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		Locked_Pet_Age = 75,
		Locked = {
			"Barn Owl", "Swan", "Marmot", "Space Squirrel", "Sugar Glider",
			"Drake",
			"Phoenix",
			["Shroomie"] = 3,
			"Cockatrice",
			"Griffin",
			"Peach Wasp",
			"Apple Gazelle",
			"Green Bean",
			"Lemon Lion",
			"Golden Goose",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"T-Rex",
			"Spinosaurus",
			"Fennec Fox",
			"Mimic Octopus",
			"Disco Bee",
			"Butterfly",
			"Raccoon",
			"Queen Bee",
			"Dragonfly",
			"Red Fox",
			"Ankylosaurus",
			"Dilophosaurus",
			"Brontosaurus",
			"Hyacinth Macaw",
			"Moth",
			"Moon Cat",
			"Night Owl",
			"Blood Owl",
			"Blood Kiwi",
			"Cooked Owl",
			"Pterodactyl",
			"Chicken Zombie",
			"Raiju",
			["Wasp"] =10,
			["Tarantula Hawk"] = 10,
			"Axolotl",
			"Echo Frog",
			"Hamster",
			["Pixie"] = 5,
			["Maneki-neko"] = 2,
			["Hotdog Daschund"] = 2,
			["Sunny-Side Chicken"] = 3,
			["Mochi Mouse"] = 1,
			["Koi"] = 2,
			["Bacon Pig"] = 1,
			["Junkbot"] = 1,
			["Starfish"] = 5,
			["Kappa"] = 1,
			["Tanchozuru"] = 2,
			["Praying Mantis"] = 5,
			["Rooster"] = 8,
			["Seal"] = 2,
			["Chicken"] = 2,
			["Golem"] = 1,
			["Bagel Bunny"] = 2,
			["Peacock"] = 3,
			["Ostrich"] = 4,
			["Sea Turtle"] = 3,
			["Scarlet Macaw"] = 2,
			["Turtle"] = 6,
			["Monkey"] = 6,
		},
		LockPet_Weight = 8,
		Instant_Sell = {
			"Glimmering Sprite",
			"Kodama",
			"Capybara",
			"Sushi Bear",
			"Polar Bear",
			"Snail",
			"Squirrel",
			"Gorilla Chef",
			"Spaghetti Sloth",
			"Imp",
			"Mandrake",
			"Jackalope",
			"Flamingo",
			"Toucan",
			"Orangutan",
			"Dairy Cow",
			"Bagel Bunny",
			"Seagull",
			"Caterpillar",
			"Corrupted Kodama",
			"Golem",
			"Bacon Pig",
			"Crab",
			"Hotdog Daschund",
			"Elk",
			"Bunny",
			"Dog",
			"Cow",
			"Sea Otter",
			"Silver Monkey",
			"Spotted Deer",
			"Pig",
			"Ladybug",
			"Orange Tabby",
			"Giant Ant",
			"Pixie",
			},
	},
	Webhook = {
		UrlPet = "",
		UrlSeed = "xxx",
		PcName = "LUCKY",
		Noti = {
			Seeds = {
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
			},
			SeedPack = {
				"Idk"
			},
			Pets = {
				"Lobster Thermidor",
				"French Fry Ferret",
			},
			Pet_Weight_Noti = false,
		}
	},
}
