return {
	Beta_Fix_Data_Sync = true,
	NoDeletePlayer = false,
	["Block Pet Gift"] = true,
	Collect_Cooldown = 120,
	["Low Cpu"] = true,
	["Auto Rejoin"] = true,
	["Rejoin When Update"] = false,
	["Limit Tree"] = {
		["Limit"] = 300,
		["Destroy Until"] = 300,

		["Safe Tree"] = {
			"Moon Blossom",
			"Bone Blossom",
			"Moon Melon",
			"Maple Apple",
			"Moon Mango",
			"Dragon Pepper",
			"Elephant Ears",
			"Fossilight",
			"Princess Thorn",
			-- for the event
			Bamboo = 2,
			Coconut = 2,
			Mushroom = 2,
			Glowthorn = 2,
			Tomato = 2,
			Pumpkin = 2,
			Pepper = 2,
			Cacao = 2,
			Apple = 2,
			Romanesco = 2,
			["Elder Strawberry"] = 2,
			["Burning Bud"] = 2,
			["Giant Pinecone"] = 2,
			Corn = 2,
			["Sugar Apple"] = 2,
			["Ember Lily"] = 2,
			["Dragon Fruit"] = 2,
			Sunbulb = 2,
			["Orange Tulip"] = 2,
			Blueberry = 2,
			Watermelon = 2,
			Mango = 2,
			Cactus = 2,
			Strawberry = 2,
			Beanstalk = 2,
			Lightshoot = 2,
			Grape = 2,
			Daffodil = 2
		}
	},
	Seed = {
		Buy = {
			Mode = "Auto", -- Custom , Auto
			Custom = { -- any fruit u need to place
				"Carrot",
			}
		},
		Place = {
			Mode = "Lock", -- Select , Lock
			Select = {
				"Carrot"
			},
			Lock = {
				"Maple Apple",
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
				"Moon Melon",
				"Easter Egg",
				"Moon Mango",
				"Bone Blossom",
				"Fossilight",
			}
		}
	},
	["Seed Pack"] = {
		Locked = {
		}
	},
	Events = {
		["Fairy Event"] = {
			Minimum_Money = 10_000_000, -- minimum money to start play this event
		},
		MaxMoney_Restocks = 500_000_001,
		Shop = { -- un comment to buy
			"Sprout Seed Pack",
			"Sprout Egg",
			-- "Mandrake",
			"Silver Fertilizer",
			-- "Canary Melon",
			-- "Amberheart",
			["Spriggan"] = 8,
			-- Friend Shop
			"Skyroot Chest",
			"Pet Shard GiantBean",
		},
		["Traveling Shop"] = {
			"Bee Egg",
		},
		Craft = {
			"Anti Bee Egg",
			"Pet Shard GiantBean",
			"Sprout Egg",
		},
		Start_Do_Honey = 2_000_000 -- start trade fruit for honey at money
	},
	Gear = {
		Buy = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
			"Level Up Lollipop",
			"Medium Treat",
			"Medium Toy",
		},
		Lock = {
			"Master Sprinkler",
			"Godly Sprinkler",
			"Advanced Sprinkler",
			"Basic Sprinkler",
			"Lightning Rod",
		},
	},
	Eggs = {
		Place = {
			"Enchanted Egg",
			--"Sprout Egg",
			--"Rare Summer Egg",
			"Paradise Egg",
			--"Gourmet Egg",
			--"Common Summer Egg",
			--"Zen Egg",
			--"Oasis Egg",
			"Night Egg",
			"Anti Bee Egg",
			--"Bug Egg",
			"Primal Egg",
			"Dinosaur Egg",
		},
		Buy = {
			"Bug Egg",
			"Bee Egg",
			"Paradise Egg",
			"Mythical Egg",
			"Rare Summer Egg",
			"Common Summer Egg",
			"Rare Egg",
		}
	},
	Pets = {
		["Auto Feed"] = true,
		["Start Delete Pet At"] = 55,
		["Upgrade Slot"] = {
			["Pet"] = {
				["Starfish"] = {5,100,1,true},
			},
			["Limit Upgrade"] = 5,
			["Equip When Done"] = {
				["Peach Wasp"] = {1,100,1},
				["Sunny-Side Chicken"] = {1,100,2},
				["Seal"] = {1,100,2},
				["Koi"] = {1,100,2},
				--["Green Bean"] = {1,100,7},
				["Wasp"] = {2,100,1},
				["Tarantula Hawk"] = {2,100,1},
				["Bee"] = {2,100,1},
			},
		},
		Unfavorite_AllPet = false,
		Favorite_LockedPet = true,
		Locked_Pet_Age = 75,
		Locked = {
			"Cockatrice",
			"Glimmering Sprite",
			["Imp"] = 2,
			"Bee",
			"Griffin",
			"Peach Wasp",
			"Apple Gazelle",
			"Green Bean",
			"Lemon Lion",
			"Golden Goose",
			"Kitsune",
			"Corrupted Kitsune",
			"French Fry Ferret",
			"Lobster Thermidor",
			"T-Rex",
			"Spinosaurus",
			"Fennec Fox",
			"Mimic Octopus",
			"Disco Bee",
			"Butterfly",
			"Raccoon",
			"Queen Bee",
			"Dragonfly",
			"Red Fox",
			"Ankylosaurus",
			"Dilophosaurus",
			"Brontosaurus",
			"Hyacinth Macaw",
			"Moth",
			"Moon Cat",
			"Night Owl",
			"Blood Owl",
			"Blood Kiwi",
			"Cooked Owl",
			"Pterodactyl",
			"Chicken Zombie",
			"Raiju",
			["Spaghetti Sloth"] = 3,
			"Wasp",
			"Tarantula Hawk",
			"Axolotl",
			"Echo Frog",
			"Hamster",
			["Maneki-neko"] = 2,
			["Squirrel"] = 2,
			["Hotdog Daschund"] = 2,
			["Sunny-Side Chicken"] = 2,
			["Gorilla Chef"] = 3,
			["Sushi Bear"] = 1,
			["Mochi Mouse"] = 1,
			["Koi"] = 2,
			["Bacon Pig"] = 1,
			["Junkbot"] = 1,
			["Starfish"] = 2,
			["Kodama"] = 2,
			["Kappa"] = 1,
			["Tanchozuru"] = 2,
			["Praying Mantis"] = 1,
			["Toucan"] = 1,
			["Capybara"] = 2,
			["Rooster"] = 2,
			["Seal"] = 2,
			["Chicken"] = 2,
			["Golem"] = 1,
			["Bagel Bunny"] = 2,
			["Peacock"] = 3,
			["Ostrich"] = 2,
			["Orange Tabby"] = 2,
			["Sea Turtle"] = 3,
			["Scarlet Macaw"] = 2
		},
		LockPet_Weight = 8,
		Instant_Sell = {
			"Mandrake",
			"Jackalope",
			"Flamingo",
			"Toucan",
			"Orangutan",
			"Dairy Cow",
			"Bagel Bunny",
			"Seagull",
			"Caterpillar",
			"Corrupted Kodama",
			"Golem",
			"Bacon Pig",
			"Crab",
			"Hotdog Daschund",
			"Elk",
			"Bunny",
			"Dog",
			},
	},
	Webhook = {
		UrlPet = "",
		UrlSeed = "xxx",
		PcName = "LUCKY",
		Noti = {
			Seeds = {
				"Sunflower",
				"Dragon Pepper",
				"Elephant Ears",
			},
			SeedPack = {
				"Idk"
			},
			Pets = {
				"Lobster Thermidor",
				"French Fry Ferret",
			},
			Pet_Weight_Noti = false,
		}
	},
}
